### ISSUE TITLE
Use a log-scale for plot variables that span more than 5 orders of magnitude.

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/spacesavers2#37]
Log-scaled axes look great with `scale_x_log10(labels = label_log(digits = 2))`, but `plotly::ggplotly()` doesn't know how to handle the expression returned by `label_log`. Need to find a workaround that doesn't mess up the axis labels.

See 11be2e0

**Comment by kopardev** [comment]
@kelly-sovacool  is this still relevant ... or can it be closed?

**Comment by kelly-sovacool** [comment]
I think the plots look fine as-is without the log scale labels. We can revisit this if we start to see a wide spread across orders of magnitude.
