### ISSUE TITLE
Krona charts

### ISSUE THREAD

**Issue by kopardev** [CCBR/spacesavers2#46]
- generate output in krona acceptable format
- create krona HTML reports like this:
<img width="1815" alt="image" src="https://github.com/CCBR/spacesavers2/assets/1882209/a37f9f96-9c92-48ed-b114-a903a0e17ff5">
- Another example --> https://hpcnihapps.cit.nih.gov/krona/sVHVgr4c0PqyvvDbb9ODxwgC.html?dataset=0&node=0&collapse=false&color=true&depth=2&font=12&key=true

**Comment by kelly-sovacool** [comment]
Maybe color by % Duplication or by Score?
