### ISSUE TITLE
add plot for percent of usage over time

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/spacesavers2#49]
for the entire data mount

**Comment by kopardev** [comment]
Remove "avail". 
<img width="1016" alt="image" src="https://github.com/CCBR/spacesavers2/assets/1882209/c330f999-2d44-4e57-8942-26ebc79e8bb6">
Also, do we only have 2 datapoints?

**Comment by kelly-sovacool** [comment]
With #60 the report now appends the results of `df` to a file so we can keep these results over time, before we were not tracking the `df` results over time.
